Replace -h|--help with h|help

diff --git a/lncfg b/lncfg
--- a/lncfg
+++ b/lncfg
@@ -17,11 +17,11 @@ cyan=$(tput setaf 6)
 reset=$(tput sgr0)
 
 function print_help() {
-  echo -e "Usage: ${0} [-h|--help] [-v|--verbose] [-d|--debug] [-D|--docs]\n" \
-    "\t[-i|--install-dir <install directory>] " \
-    "[-B|--build-dir <build directory>\n" \
+  echo -e "Usage: ${0} [h|help] [-b|--build-type] <build-type>\n" \
+    "\t[-e|--enable-docs]\n\t[-i|--install-dir <install directory>]\n" \
+    "\t[-B|--build-dir <build directory>\n" \
     "\t[-o|--opencl-lib <opencl library>]\n" \
-    "${cyan}-h/--help:${reset} Print help for libnomp configuration script.\n" \
+    "${cyan}h/help:${reset} Print help for libnomp configuration script.\n" \
     "${cyan}-b/--build-type:${reset} Specify the build type for cmake " \
     "(Default: ${NOMP_BUILD_TYPE}, Allowed: Debug, Release, RelWithDebInfo " \
     "and MinSizeRel).\n" \
@@ -38,16 +38,17 @@ function print_help() {
 # parse the options
 while [ $# -gt 0 ]; do
   case $1 in
-  -h | --help) print_help ;;
+  h | help) print_help ;;
   -b | --build-type) shift && NOMP_BUILD_TYPE=${1^^} ;;
   -d | --enable-docs) NOMP_ENABLE_DOCS="ON" ;;
   -i | --install-dir) shift && NOMP_INSTALL_DIR=$(realpath "${1}") ;;
   -B | --build-dir) shift && NOMP_BUILD_DIR=$(realpath "${1}") ;;
   -o | --opencl-lib) shift && NOMP_OPENCL_LIBRARY=$(realpath "${1}") ;;
-  *) echo "${red}Invalid argument: ${1}${reset}"
-    echo "See ${cyan}./lncfg -h${reset} or ${cyan}./lncfg --help${reset} for " \
-      "the accepted commands."
-    exit 1 ;;
+  *)
+    echo "${red}Invalid argument: ${1}${reset}"
+    echo "See ${cyan}lnrun h|help${reset} for the accepted commands."
+    exit 1
+    ;;
   esac
   shift
 done
diff --git a/scripts/lnrun b/scripts/lnrun
--- a/scripts/lnrun
+++ b/scripts/lnrun
@@ -33,7 +33,7 @@ function print_help_main() {
     "\t${cyan}D${reset}, ${cyan}docs${reset} \t Open the user documentation " \
     "on the web browser.\n\n" \
     "To view the usage of each command, execute ${cyan}lnrun -h " \
-    "<command>${reset} or ${cyan}lnrun --help <command>${reset}."
+    "<command>${reset} or ${cyan}lnrun help <command>${reset}."
 }
 
 function print_help_test() {
@@ -155,7 +155,7 @@ fi
 # parse the command
 while [ $# -gt 0 ]; do
   case $1 in
-  -h | --help)
+  h | help)
     shift
     case $1 in
     t | test) print_help_test ;;
@@ -175,10 +175,12 @@ while [ $# -gt 0 ]; do
       -b | --backend) shift && NOMP_BACKEND="${1}" ;;
       -p | --platform) shift && NOMP_PLATFORM="${1}" ;;
       -d | --device) shift && NOMP_DEVICE="${1}" ;;
-      *) echo "${red}Invalid argument: ${1}${reset}" &&
-        echo "See ${cyan}lnrun -h t|test ${reset} or ${cyan}lnrun" \
-          "--help t|test ${reset} for the accepted commands."
-        exit 1 ;;
+      *)
+        echo "${red}Invalid argument: ${1}${reset}" &&
+          echo "See ${cyan}lnrun h t|test ${reset} or ${cyan}lnrun" \
+            "help t|test ${reset} for the accepted commands."
+        exit 1
+        ;;
       esac
       shift
     done
@@ -194,10 +196,11 @@ while [ $# -gt 0 ]; do
       -b | --backend) shift && NOMP_BACKEND="${1}" ;;
       -p | --platform) shift && NOMP_PLATFORM="${1}" ;;
       -d | --device) shift && NOMP_DEVICE="${1}" ;;
-      *) echo "${red}Invalid argument: ${1}${reset}" &&
-        echo "See ${cyan}lnrun -h d|debug ${reset} or ${cyan}lnrun" \
-          "--help d|debug ${reset} for the accepted commands."
-        exit 1 ;;
+      *)
+        echo "${red}Invalid argument: ${1}${reset}" &&
+          echo "See ${cyan}lnrun h|help d|debug${reset} for the accepted commands."
+        exit 1
+        ;;
       esac
       shift
     done
@@ -208,19 +211,21 @@ while [ $# -gt 0 ]; do
     while [ $# -gt 0 ]; do
       case $1 in
       -B | --browser) shift && NOMP_BROWSER="${1}" ;;
-      *) echo "${red}Invalid argument: ${1}${reset}" &&
-        echo "See ${cyan}lnrun -h D|docs ${reset} or ${cyan}lnrun" \
-          "--help D|docs ${reset} for the accepted commands."
-        exit 1 ;;
+      *)
+        echo "${red}Invalid argument: ${1}${reset}" &&
+          echo "See ${cyan}lnrun h|help D|docs${reset} for the accepted commands."
+        exit 1
+        ;;
       esac
       shift
     done
     open_docs
     ;;
-  *) echo "${red}Invalid argument: ${1}${reset}" &&
-    echo "See ${cyan}lnrun -h${reset} or ${cyan}lnrun --help${reset} for" \
-      "the accepted commands."
-    exit 1 ;;
+  *)
+    echo "${red}Invalid argument: ${1}${reset}" &&
+      echo "See ${cyan}lnrun h|help${reset} for the accepted commands."
+    exit 1
+    ;;
   esac
   shift
 done
