Refactor lninstall script
and minor changes in lncfg script.

diff --git a/lninstall b/lninstall
--- a/lninstall
+++ b/lninstall
@@ -1,31 +1,38 @@
 #!/bin/bash
 
-# script variables
-NOMP_SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-NOMP_DEFAULT_PROMPT=""
-NOMP_LNSTATE_PATH="${NOMP_SOURCE_DIR}/.lnstate"
-NOMP_SHELL_CONFIG_FILE=""
+# Script variables.
+: "${NOMP_SOURCE_DIR:="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"}"
+: "${NOMP_SHELL_CONFIG_FILE:="${HOME}/.bashrc"}"
 
-# colors
+# Terminal output colors.
 red=$(tput setaf 1)
 green=$(tput setaf 2)
 cyan=$(tput setaf 6)
 reset=$(tput sgr0)
 
-# read state variables of lncfg
+# Read state variables created by lncfg.
+NOMP_LNSTATE_PATH="${NOMP_SOURCE_DIR}/.lnstate"
 if [[ -f "${NOMP_LNSTATE_PATH}" ]]; then
   source "${NOMP_LNSTATE_PATH}"
 else
-  echo "${red}You should run ./lncfg before running ./${0}${reset}"
+  echo "${red}You should run ./lncfg before running ./${0}${reset}."
   exit 1
 fi
-NOMP_BIN_PATH="${NOMP_INSTALL_DIR}/bin"
+if [[ ! -v NOMP_INSTALL_DIR ]]; then
+  echo "${red}NOMP_INSTALL_DIR is not set in .lnstate file${reset}."
+  exit 1
+fi
 
-# check the shell config file
-if [[ -f ~/.bashrc ]]; then
-  NOMP_SHELL_CONFIG_FILE="${HOME}/.bashrc"
-elif [[ -f ~/.zshrc ]]; then
-  NOMP_SHELL_CONFIG_FILE="${HOME}/.zshrc"
+# Check if the specified shell configuration file exists. If not, look for
+# common config files.
+if [[ ! -f "${NOMP_SHELL_CONFIG_FILE}" ]]; then
+  if [[ -f "${HOME}/.bashrc" ]]; then
+    NOMP_SHELL_CONFIG_FILE="${HOME}/.bashrc"
+  elif [[ -f "${HOME}/.zshrc" ]]; then
+    NOMP_SHELL_CONFIG_FILE="${HOME}/.zshrc"
+  else
+    NOMP_SHELL_CONFIG_FILE=""
+  fi
 fi
 
 function update_bashrc() {
@@ -36,47 +43,49 @@ function update_bashrc() {
   exit 0
 }
 
+# Check if the user asked us to update the shell configuration.
+NOMP_DEFAULT_PROMPT=""
 function print_help() {
-  echo -e "Usage: ${0} [-h|--help] [-y|--yes] [-n|--no]\n" \
+  echo -e "Usage: ${0} [-h|--help] [-n|--no] [-y|--yes]\n" \
     "${cyan}-h/--help:${reset} Print help for libnomp install.\n" \
-    "${cyan}-y/--yes:${reset} Yes to all prompts.\n" \
-    "${cyan}-n/--no:${reset} No to all prompts."
+    "${cyan}-n/--no:${reset} Don't update shell configuration file.\n" \
+    "${cyan}-y/--yes:${reset} Update shell configuration file."
   exit 0
 }
 
-# check for default prompt
 if [[ $# -gt 0 ]]; then
   case $1 in
     -h | --help) print_help ;;
-    -y | --yes) NOMP_DEFAULT_PROMPT="y" ;;
     -n | --no) NOMP_DEFAULT_PROMPT="n" ;;
-    *) echo "${red}Invalid argument: ${1}${reset}."
+    -y | --yes) NOMP_DEFAULT_PROMPT="y" ;;
+    *) echo "${red}Invalid option: ${1}${reset}."
     echo "See ${cyan}./${0} -h${reset} or ${cyan}./${0} --help${reset} for" \
-      "the accepted commands."
+      "the accepted options."
     exit 1 ;;
   esac
 fi
 
-# installing libnomp
+# Create the commands which goes in shell configuration.
+NOMP_ENVIRONMENT=$(cat <<-END
+# Setup nomp environment variables.
+export NOMP_INSTALL_DIR=${NOMP_INSTALL_DIR}
+# Add lnrun script to path.
+export PATH=${NOMP_INSTALL_DIR}/bin:\${PATH}
+END
+)
+
+# Installing libnomp.
 NOMP_INSTALL_SUCCESS=false
 cmake --build "${NOMP_BUILD_DIR}" --target install &&
   NOMP_INSTALL_SUCCESS=true
 
 if [[ ${NOMP_INSTALL_SUCCESS} = true ]]; then
-  echo "${green}Successfully installed libnomp${reset}"
+  echo "${green}Successfully installed libnomp${reset}."
   echo "See ${cyan}lnrun -h${reset} or ${cyan}lnrun --help${reset} for " \
     "available commands."
 
   [[ ${NOMP_DEFAULT_PROMPT} = "n" ]] && exit 0
-
-  # Add nomp install dir to env
-  NOMP_ENVIRONMENT=$(cat <<-END
-# Setup nomp environment variables
-export NOMP_INSTALL_DIR=${NOMP_INSTALL_DIR}
-# Add lnrun script to path
-export PATH=${NOMP_BIN_PATH}:\${PATH}
-END
-)
+  [[ -z "${NOMP_SHELL_CONFIG_FILE}" ]] && exit 0
 
   # set the libnomp env variables if not
   [[ ${NOMP_DEFAULT_PROMPT} = "y" ]] && update_bashrc
